In [30]:
import sys
from pathlib import Path

sys.path.insert(0, str(Path('..').resolve()))

from src.data_structures.linked_list import Linked_List_Compra, Linked_List_Venda

from src.data_structures.node import Node
from src.data_structures.ordem import Ordem
from src.data_structures.queue import Queue
from src.data_structures.stack import Stack

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import time

In [31]:
# TODO: mudar o path para funcionar em outros pc's
dados = '/mnt/hd/trabalho-ed/Trabalho-ED/orders.csv'
df = pd.read_csv(dados)
novo_ID = df['ID'].convert_dtypes(convert_floating=True)
nova_quantidade = df['Quantity'].convert_dtypes(convert_floating=True)
df['Quantity'] = nova_quantidade
df['ID'] = novo_ID
df
df.head()

   ID Type  Price  Quantity            Timestamp
0   1    C  66.96       750  2026-06-16 01:26:58
1   2    C  28.11       160  2026-06-16 01:27:02
2   3    C  54.85       290  2026-06-16 01:27:07
3   4    V  70.40       120  2026-06-16 01:27:08
4   5    V  47.11       480  2026-06-16 01:27:10

In [32]:
# Adicionar elementos 'C' à lista de compras
# Adicionar elementos 'V' à lista de vendas
# Ver tempo de demora de matchs
# Mostrar que inserção em qualquer ponto das listas segue O(n)
# Mostrar que push/pop, enqueue/dequeue seguem O(1)

In [33]:
df_compras = df.where(df['Type']=='C').dropna()
df_compras.count()
df_compras

         ID Type  Price  Quantity            Timestamp
0         1    C  66.96       750  2026-06-16 01:26:58
1         2    C  28.11       160  2026-06-16 01:27:02
2         3    C  54.85       290  2026-06-16 01:27:07
8         9    C  65.36       430  2026-06-16 01:27:23
14       15    C  23.52       670  2026-06-16 01:27:42
...     ...  ...    ...       ...                  ...
9987   9988    C  18.62       710  2026-06-16 09:44:12
9992   9993    C  66.67       680  2026-06-16 09:44:29
9995   9996    C  60.73       990  2026-06-16 09:44:37
9998   9999    C  15.75       470  2026-06-16 09:44:48
9999  10000    C  59.07       480  2026-06-16 09:44:49

[4953 rows x 5 columns]

In [34]:
df_vendas = df.where(df['Type']=='V').dropna()
df_vendas.count()
df_vendas

        ID Type  Price  Quantity            Timestamp
3        4    V  70.40       120  2026-06-16 01:27:08
4        5    V  47.11       480  2026-06-16 01:27:10
5        6    V  39.14       720  2026-06-16 01:27:15
6        7    V  31.60       810  2026-06-16 01:27:20
7        8    V  44.76       560  2026-06-16 01:27:21
...    ...  ...    ...       ...                  ...
9991  9992    V  92.39       360  2026-06-16 09:44:24
9993  9994    V  55.68       620  2026-06-16 09:44:30
9994  9995    V  97.36       670  2026-06-16 09:44:34
9996  9997    V  77.12       700  2026-06-16 09:44:41
9997  9998    V  36.66       870  2026-06-16 09:44:44

[5047 rows x 5 columns]

In [35]:
df_vendas.shape[0]

5047

In [36]:
id_ordem = df.loc[0, 'Type']
print(id_ordem)

C

In [37]:
lista_venda = Linked_List_Venda()
IDs_vendas = df_vendas['ID'].to_list()

inicio = time.time()

for i in IDs_vendas: # df['ID] é uma unidade maior que os índices do df. Por isso usamos i-1
    ordem1 = Ordem(
        id_ordem = df_vendas.loc[i-1, 'ID'],
        tipo = df_vendas.loc[i-1, 'Type'],
        preco = df_vendas.loc[i-1, 'Price'],
        quantidade = df_vendas.loc[i-1, 'Quantity']
    )
    acao1 = Node(ordem1)
    
    lista_venda.adicionar_no(acao1)

fim = time.time()

tempo = fim - inicio
print(tempo)

1.6944642066955566

In [38]:
lista_compra = Linked_List_Compra()
IDs_compras = df_compras['ID'].to_list()

inicio = time.time()

for i in IDs_compras: # df['ID] é uma unidade maior que os índices do df. Por isso usamos i-1



    ordem1 = Ordem(
        id_ordem = df_compras.loc[i-1, 'ID'],
        tipo = df_compras.loc[i-1, 'Type'],
        preco = df_compras.loc[i-1, 'Price'],
        quantidade = df_compras.loc[i-1, 'Quantity']
    )
    acao1 = Node(ordem1)
    
    lista_compra.adicionar_no(acao1)

fim = time.time()

tempo_execucao = fim - inicio

print(tempo_execucao)

2.04471492767334

In [39]:
ordem_meio_compra = Ordem(
        id_ordem = lista_compra.retorna_tamanho()//2,        
        tipo = 'C',
        preco = 150,
        quantidade = 20
    )
acao_meio = Node(ordem_meio_compra)

inicio = time.time()

lista_compra.adicionar_no_meio(acao_meio)

fim = time.time()

tempo_execucao = fim - inicio

print(tempo_execucao)

0.0006947517395019531

In [40]:
ordem_meio_venda = Ordem(
        id_ordem = lista_venda.retorna_tamanho()//2,        
        tipo = 'V',
        preco = 120,
        quantidade = 30
    )
acao_meio_venda = Node(ordem_meio_venda)

inicio = time.time()

lista_venda.adicionar_no_meio(acao_meio_venda)

fim = time.time()

tempo_execucao = fim - inicio

print(tempo_execucao)

0.0005507469177246094

In [41]:
pilha_compra = Stack()


inicio = time.time()

for i in IDs_compras: # df['ID] é uma unidade maior que os índices do df. Por isso usamos i-1
    ordem1 = Ordem(
        id_ordem = df_compras.loc[i-1, 'ID'],
        tipo = df_compras.loc[i-1, 'Type'],
        preco = df_compras.loc[i-1, 'Price'],
        quantidade = df_compras.loc[i-1, 'Quantity']
    )
    acao1 = Node(ordem1)
    
    pilha_compra.empilhar(acao1)

fim = time.time()

tempo_execucao = fim - inicio

print('Tempo para empilhar')
print(tempo_execucao)

inicio = time.time()
pilha_compra.desempilhar()
fim = time.time()

print('\nTempo para desimpilhar')
print(fim-inicio)

Tempo para empilhar
0.6896700859069824

Tempo para desimpilhar
0.00011277198791503906

In [42]:
queue_compra = Queue()


inicio = time.time()
for i in IDs_compras: # df['ID] é uma unidade maior que os índices do df. Por isso usamos i-1
    ordem1 = Ordem(
        id_ordem = df_compras.loc[i-1, 'ID'],
        tipo = df_compras.loc[i-1, 'Type'],
        preco = df_compras.loc[i-1, 'Price'],
        quantidade = df_compras.loc[i-1, 'Quantity']
    )
    acao1 = Node(ordem1)
    
    queue_compra.enqueue(acao1)

fim = time.time()

tempo_execucao = fim - inicio

print('Tempo para enqueue')
print(tempo_execucao)

inicio = time.time()
queue_compra.dequeue
fim = time.time()

print('\nTempo para dequeue')
print(fim-inicio)

Tempo para enqueue
0.7173657417297363

Tempo para dequeue
4.1961669921875e-05